language: bash

install:
  - mkdir ~/bats ~/prefix 
  - git clone https://github.com/sstephenson/bats.git ~/bats
  - ~/bats/install.sh ~/prefix

script:
  - ~/prefix/bin/bats test
  - ./scripts/package_self.sh
